# Generated by Django 5.0.2 on 2024-03-10 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=20)),
                ('PHONENUMBER', models.IntegerField(max_length=20)),
                ('E_MAIL', models.CharField(max_length=25)),
                ('MESSAGE', models.CharField(max_length=100)),
            ],
        ),
    ]
