# Generated by Django 5.0.2 on 2024-03-10 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='E_MAIL',
        ),
        migrations.AddField(
            model_name='child',
            name='EMAIL',
            field=models.EmailField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='child',
            name='PHONENUMBER',
            field=models.CharField(max_length=20),
        ),
    ]
