# Generated by Django 5.0.2 on 2024-03-10 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_child_e_mail_child_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='EMAIL',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='child',
            old_name='MESSAGE',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='child',
            old_name='NAME',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='child',
            old_name='PHONENUMBER',
            new_name='phonenumber',
        ),
    ]
