# Generated by Django 5.0.2 on 2024-03-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_email_child_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
